### ISSUE TITLE
[Feature Request] Server invite on store page

### ISSUE THREAD

**Issue by TheGoldenCactus11** [discord/gamesdk-and-dispatch#70] opened 2020-05-15 08:46 UTC
Hey!

You know the official server panel on store pages for verified servers, I think this should be here for all game dev pages, and you should not have to verify your server first.

Thanks.

**Comment by Jump-Suit** [comment] 2020-05-15 14:56
Duplicate of: https://github.com/discord/gamesdk-and-dispatch/issues/44

**Closed** 2020-05-15 15:01 UTC
